image: "python:3.7"

variables:
  CBT_USERNAME: "YOUR_USERNAME"
  CBT_AUTHKEY: "YOUR_AUTHKEY"

run_test:
    script:
        - pip install selenium 
        - pip install requests
        - python sel_test.py
